version: '2'

services:
  substrate:
    container_name: substrate
    image: parity/polkadot:v0.9.29
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    command: --dev --rpc-external --ws-external --rpc-methods Unsafe --offchain-worker Always
